#!/bin/python3

bool1 = True
bool2 = 3*3 == 9
bool3 = False
bool4 = 3*3 != 9
print(bool1,bool2,bool3,bool4)

print(type(bool1))



#Relational and BOOLEAN OPERATORS
greater_than = 7 > 5

less_than = 5 < 7

greater_than_equal_to = 7 >= 7

less_than_equal_to = 5 <= 7

test_and = (7 > 5) and (5 < 7) # True

test_and2 = (7 > 5) and (5 > 7) # False

test_or = (7 > 5) or (5 < 7) # True

test_or2 = (7 > 5) or (5 > 7) # True

print(test_and, test_and2, test_or, test_or2)
